#!/usr/bin/env bash

#paq 
git clone https://github.com/savq/paq-nvim.git \
    "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/pack/paqs/opt/paq-nvim

# conf
mkdir -p ~/.config/nvim
cp -r ./nvim/init.lua ./nvim/lua  ~/.config/nvim/

# Language servers
yarn global add bash-language-server
yarn global add vscode-css-languageserver-bin
go get golang.org/x/tools/gopls@latest
yarn global add vscode-html-languageserver-bin
yarn global add vscode-json-languageserver
pip install python-language-server
brew install rust-analyzer
yarn global add typescript typescript-language-server
yarn global add yaml-language-server

echo "Run `nvim +PaqInstall` to finish setup"
